[package]
name = "ligen"
version = "0.1.0"
authors = ["Danilo Guanabara Fernandes"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.1"
syn = { version = "1.0.2", features = [ "full" ] }
quote = "1.0"
ligen-core = { path = "../ligen-core" }
